### PR TITLE
GitHub workflows for testing & publishing

### PR DESCRIPTION
**Pull request by phdenzel**
- workflow for running pytest on Python version 3.10, 3.11., 3.12
- workflow for publishing pushes and PR to main as releases, packages to TestPyPI, and tagged pushes and PR to PyPI

### CODE REVIEW

**Comment by phdenzel** [comment]
We should probably introduce a pre-release versioning scheme, so we don't have conflicts with PyPI and especially Test PyPI.

**Comment by bil-y** [comment]
> We should probably introduce a pre-release versioning scheme, so we don't have conflicts with PyPI and especially Test PyPI.

We could add the git hash to the version, but I don't see an immediate option to achieving this with hatch / pip / build.

**Comment by phdenzel** [comment]
> > We should probably introduce a pre-release versioning scheme, so we don't have conflicts with PyPI and especially Test PyPI.
> 
> We could add the git hash to the version, but I don't see an immediate option to achieving this with hatch / pip / build.

I figured out how to skip the test-pypi build when the version already exists... so, if we need to test a new build, we just have to change the version manually. I think that's good enough for now, everything else is automated.

**Comment by bil-y** [comment]
> > > We should probably introduce a pre-release versioning scheme, so we don't have conflicts with PyPI and especially Test PyPI.
> > 
> > 
> > We could add the git hash to the version, but I don't see an immediate option to achieving this with hatch / pip / build.
> 
> I figured out how to skip the test-pypi build when the version already exists... so, if we need to test a new build, we just have to change the version manually. I think that's good enough for now, everything else is automated.

Never mind my previous reply, there is `hatch version [version string]`. The version string has to be [PEP440](https://peps.python.org/pep-0440/) compliant. PEP440 defines both a "public" and a "local" version string.

So, after a release, we could bumb the patch version and add a `dev1`. E.g. `0.0.1 -> 0.0.2.dev1`
Then, using the local version, we can do the following: `0.0.2.dev1+[commit hash]`

**Comment by phdenzel** [comment]
Workflow "executive summary":
- for PR to main:
  - building & testing Python 3.10, 3.11, 3.12 
  - automatic publishing to TestPyPI (if version is new)
  - auto bump dev version (e.g. `0.0.1.dev3 -> 0.0.1.dev4`)
- for tagged pushes on main:
  - building & testing Python 3.10, 3.11, 3.12
  - automatic publishing to PyPI (if version is new)
  - auto bump micro version (e.g. `0.0.1 -> 0.0.2`)

**Comment by phdenzel** [comment]
Ready to be merged from my side.

**Review by mstadelmann — APPROVED** [review]

**Pull request merged**
